// Generated by CIRCT d6e1fc8ed
module OrInts(	// {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/module.py:491 <- /home/rick/Desktop/fpga_compiler/testing_examples/pycde/example.py:8}
  input  [31:0] a,
                b,
  output [31:0] c
);

  assign c = a | b;	// {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/module.py:114 <- {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/module.py:119 <- {/home/rick/Desktop/fpga_compiler/testing_examples/pycde/example.py:13 <- /home/rick/Desktop/fpga_compiler/testing_examples/pycde/example.py:8}}}, {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/signals.py:1245 <- {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/signals.py:435 <- {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/signals.py:454 <- {/home/rick/Desktop/fpga_compiler/testing_examples/pycde/example.py:15 <- {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/module.py:600 <- {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/system.py:352 <- {/home/rick/Desktop/fpga_compiler/venv/lib/python3.14/site-packages/pycde/system.py:516 <- /home/rick/Desktop/fpga_compiler/testing_examples/pycde/example.py:19}}}}}}}
endmodule

